export const brawlersData = [
  {
      id: 1,
      nomeEng: 'Rico',
      nomeIta: 'Stecca',
      descrizione: 'E’ un Brawler Super Raro con un basso livello di salute e un danno moderato, ma è unico per il fatto che i suoi proiettili  possono rimbalzare sui muri e continuare a viaggiare.',
      url: 'https://brawlstars.fandom.com/wiki/Rico',
      trofei: 61,
      puntiVita: 3380,
      attacco:416,
      avatar: 'https://i.ibb.co/J5mVm7G/Rico-Avatar.png',
      brawlerImage: 'https://i.ibb.co/VjGQ1MK/Rico.png',
      active: true,
      edit: false,
  },
  {
      id: 2,
      nomeEng: 'Rosa',
      nomeIta: 'Rosa',
      descrizione: 'Rosa è un brawler raro che attacca tre volte con i suoi guantoni da boxe. Rosa ha una buona salute, rendendola in grado di resistere a molti danni.',
      url: 'https://brawlstars.fandom.com/wiki/Rosa',
      trofei: 34,
      puntiVita: 7020,
      attacco:598,
      avatar: 'https://i.ibb.co/vzGXs7V/Rosa-Avatar.png',
      brawlerImage: 'https://i.ibb.co/FYWFG4z/Rosa.png',
      active: false,
      edit: false,
  },
  {
      id: 3,
      nomeEng: 'Bo',
      nomeIta: 'Bo',
      descrizione: 'Bo ha una salute abbastanza alta e spara frecce esplosive che infliggono danni moderati a lunga distanza.',
      url: 'https://brawlstars.fandom.com/wiki/Bo',
      trofei: 15,
      puntiVita: 4680,
      attacco:676,
      avatar: 'https://i.ibb.co/s22zdm7/BoAvatar.png',
      brawlerImage: 'https://i.ibb.co/khCkQDG/Bo.png',
      active: false,
      edit: false,
  },
  {
      id: 4,
      nomeEng: 'Jessie',
      nomeIta: 'Jessie',
      descrizione: 'Jessie stessa ha una salute media ed è in grado di fare danni elevati. Può posizionare una torretta ottima per distrarre gli avversari e fornire supporto e difesa.',
      url: 'https://brawlstars.fandom.com/wiki/Jessie',
      trofei: 53,
      puntiVita: 4160,
      attacco:1092,
      avatar: 'https://i.ibb.co/nsmfrVG/Jessie-Avatar.png',
      brawlerImage: 'https://i.ibb.co/4dd6B56/Jessie.png',
      active: false,
      edit: false,
  },
  {
      id: 5,
      nomeEng: 'Penny',
      nomeIta: 'Penny',
      descrizione: 'Penny ha salute media e un attacco a lungo raggio che esplode quando colpisce un bersaglio. Il suo mortaio ha una salute discreta e fa danni elevati',
      url: 'https://brawlstars.fandom.com/wiki/Penny',
      trofei: 12,
      puntiVita: 4160,
      attacco:1170,
      avatar: 'https://i.ibb.co/h7SHwh0/Penny-Avatar.png',
      brawlerImage: 'https://i.ibb.co/8d7ghbw/Penny.png',
      active: false,
      edit: false,
  },
  {
      id: 6,
      nomeEng: 'Colt',
      nomeIta: 'Colt',
      descrizione: 'Colt spara da lontano con due pistole. Ha una stellina dietro il vestito. Curiosità: ha due pistole ma ha una sola fondina.',
      url: 'https://brawlstars.fandom.com/wiki/Colt',
      trofei: 0,
      puntiVita: 3640,
      attacco:416,
      avatar: 'https://i.ibb.co/Kj2YDkQ/Colt-Avatar.png',
      brawlerImage: 'https://i.ibb.co/LgBHjVb/Colt.png',
      active: false,
      edit: false,
  },
  {
      id: 7,
      nomeEng: 'Jacky',
      nomeIta: 'Jacky',
      descrizione: 'Quando attacca, salta sul suo martello pneumatico come una pogo stick e infligge ingenti danni ad area. Jacky ha anche una buona salute, rendendola in grado di resistere a molti danni.',
      url: 'https://brawlstars.fandom.com/wiki/Jacky',
      trofei: 55,
      puntiVita: 7150,
      attacco:  1560,
      avatar: 'https://i.ibb.co/j5mnSPv/Jacky-Avatar.png',
      brawlerImage: 'https://i.ibb.co/WV0XmNF/Jacky.png',
      active: false,
      edit: false,
  },

 
];

export const snipersData = [
    {
      id: 1,
      nome: 'Jack',
      soprannome: '...sta in cucina con Tina',
      descrizione: 'Me la sono giocata di fino, senza fretta...',
      trofei: 29,
      kill: 1,
      danni: 150,
      partite: 1,
      posizioni: 2,
      sniperImage: 'https://i.ibb.co/hFv1fwp/Jack-530-255.jpg',
      active: true,
      edit: false,
    },

    {
      id: 2,
      nome: 'Samantha',
      soprannome: '...la salamantra',
      descrizione: 'Non è giusto!! Ha giocato di meno!!',
      trofei: 189,
      kill: 11,
      danni: 963,
      partite: 7,
      posizioni: 20,
      sniperImage: 'https://i.ibb.co/BP1RHdw/Samantha-530-255.jpg',
      active: false,
      edit: false,
    }
]

